#!/usr/bin/env bash
if [ ! -f "${LOGISIM_PATH}" ]; then
    echo "\$LOGISIM_PATH is either not set or does not exist.  Please set this environment variable."
    exit 1
fi

if [ $# -eq 0 ]; then
    echo "No arguments supplied!"
    exit 2
fi

circuit="cpus/$1.circ"

if [ ! -f $circuit ]; then
    echo "${circuit} does not exist!"
    exit 3
fi

java -jar $LOGISIM_PATH cpus/$1.circ &