#!/usr/bin/env bash
if [ $# -eq 0 ]; then
    echo "No arguments supplied!"
    exit 1
fi

circuit="cpus/$1.circ"

if [ ! -f $circuit ]; then
    echo "${circuit} does not exist!"
    exit 1
fi

java -jar ~/Applications/logisim.jar cpus/$1.circ &