#!/usr/bin/env bash

#!/usr/bin/env bash
if [ $# -lt 2 ]; then
    echo "Not enough arguments supplied!"
    exit 1
fi

circuit="cpus/$1.circ"
program="programs/$2.raw"

if [ ! -f $circuit ]; then
    echo "${circuit} does not exist!"
    exit 1
fi

if [ ! -f $program ]; then
    echo "${program} does not exist!"
    exit 1
fi

java -jar ~/Applications/logisim.jar "${circuit}" -tty speed -load "${program}"
